In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
A = np.array([1,2,3])
B = np.array([4,5,6])

In [8]:
res_dot = np.dot(A,B)
print(res_dot)

32


In [14]:
A = np.array([[2,3],[4,5]])
B = np.array([[1,2],[3,4]])

In [15]:
res_inn = np.inner(A,B)
print(res_inn)

[[ 8 18]
 [14 32]]


In [16]:
res_out = np.outer(A,B)
print(res_out)

[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]


In [17]:
A = np.array([[1,7],[6,9]])
print(np.linalg.det(A))

-33.0


In [18]:
A = np.array([[2,4],[6,8]])

b = np.array([5,6])

x = np.linalg.solve(A,b)

print(x)

[-2.    2.25]


In [28]:
X = np.array([[1,2],[1,3],[1,4],[1,5],[1,6]])

Y = np.array([60,75,82,90,95])

theta = np.linalg.lstsq(X,Y)[0]

print(theta)

[46.4  8.5]


C:\Users\AAYUSH KOUL\AppData\Local\Temp\ipykernel_2680\3975177780.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  theta = np.linalg.lstsq(X,Y)[0]
